Repository utfpr/reservaEquipamentosLab, pull requests merged in 2018-05, with the labels that each got.

#33 Sidebar and Home template
  Labcontrol/package-lock.json
  Labcontrol/package.json
  Labcontrol/src/App.vue
  Labcontrol/src/components/Cadastro.vue
  Labcontrol/src/components/Equipamento.vue
  Labcontrol/src/components/Home.vue
  Labcontrol/src/components/Login.vue
  Labcontrol/src/main.js
  Labcontrol/src/router/index.js
Labels: in progress

#34 fixing validate issue
  Labcontrol/src/components/Cadastro.vue
  Labcontrol/src/components/Equipamento.vue
  Labcontrol/src/main.js
Labels: in progress

#35 home changes
  Labcontrol/src/components/Equipamento.vue
  Labcontrol/src/components/Home.vue
Labels: in progress

#36 Push equipment to db
  Labcontrol/package-lock.json
  Labcontrol/src/components/Equipamento.vue
Labels: Backend, in progress

#37 Fixing infinite loading bug
  Labcontrol/src/components/Equipamento.vue
Labels: in progress

#38 hidding alert in resend E-mail action
  Labcontrol/src/components/VerificarEmail.vue
Labels: in progress

#43 update local/equipamento.vue
  Labcontrol/src/components/Equipamento.vue
  Labcontrol/src/components/Local.vue
Labels: in progress

#44 conflict merge
  Labcontrol/src/components/Equipamento.vue
Labels: in progress

#45 add local registration, update form buttons
  Labcontrol/src/components/Equipamento.vue
  Labcontrol/src/components/Local.vue
Labels: Backend, Frontend, in progress

#46 fix equipment, location registration
  Labcontrol/src/components/Equipamento.vue
  Labcontrol/src/components/Local.vue
Labels: in progress
